// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentFile() {
  return window['go']['main']['App']['ClearCurrentFile']();
}

export function ConvertFileToEnglish(arg1) {
  return window['go']['main']['App']['ConvertFileToEnglish'](arg1);
}

export function ConvertToBritish(arg1, arg2) {
  return window['go']['main']['App']['ConvertToBritish'](arg1, arg2);
}

export function ConvertToBritishWithUnits(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertToBritishWithUnits'](arg1, arg2, arg3);
}

export function DetectLanguage(arg1) {
  return window['go']['main']['App']['DetectLanguage'](arg1);
}

export function GetAmericanToBritishDictionary() {
  return window['go']['main']['App']['GetAmericanToBritishDictionary']();
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function GetSyntaxHighlightedHTML(arg1, arg2) {
  return window['go']['main']['App']['GetSyntaxHighlightedHTML'](arg1, arg2);
}

export function GetUnitProcessingStatus() {
  return window['go']['main']['App']['GetUnitProcessingStatus']();
}

export function HandleDroppedFile(arg1) {
  return window['go']['main']['App']['HandleDroppedFile'](arg1);
}

export function HandleFileService(arg1) {
  return window['go']['main']['App']['HandleFileService'](arg1);
}

export function HandleService(arg1, arg2) {
  return window['go']['main']['App']['HandleService'](arg1, arg2);
}

export function SaveConvertedFile(arg1) {
  return window['go']['main']['App']['SaveConvertedFile'](arg1);
}

export function SetUnitProcessingEnabled(arg1) {
  return window['go']['main']['App']['SetUnitProcessingEnabled'](arg1);
}
