// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentFile() {
  return window['go']['main']['App']['ClearCurrentFile']();
}

export function ConvertFileToEnglish(arg1) {
  return window['go']['main']['App']['ConvertFileToEnglish'](arg1);
}

export function ConvertToAmerican(arg1, arg2) {
  return window['go']['main']['App']['ConvertToAmerican'](arg1, arg2);
}

export function ConvertToBritish(arg1, arg2) {
  return window['go']['main']['App']['ConvertToBritish'](arg1, arg2);
}

export function GetAmericanToBritishDictionary() {
  return window['go']['main']['App']['GetAmericanToBritishDictionary']();
}

export function GetBritishToAmericanDictionary() {
  return window['go']['main']['App']['GetBritishToAmericanDictionary']();
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function HandleDroppedFile(arg1) {
  return window['go']['main']['App']['HandleDroppedFile'](arg1);
}

export function SaveConvertedFile(arg1) {
  return window['go']['main']['App']['SaveConvertedFile'](arg1);
}
