// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentFile():Promise<void>;

export function ConvertFileToEnglish(arg1:string):Promise<void>;

export function ConvertToAmerican(arg1:string,arg2:boolean):Promise<string>;

export function ConvertToBritish(arg1:string,arg2:boolean):Promise<string>;

export function GetCurrentFilePath():Promise<string>;

export function HandleDroppedFile(arg1:string):Promise<string>;

export function SaveConvertedFile(arg1:string):Promise<void>;
